name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.0

      - name: Install dependencies and deploy to EC2
        run: |
          npm install
          npm install -g pm2 
          git push origin main
          npm install
          pm2 start server.js
        env:
          HOST: http://54.81.156.64/
          USERNAME: ec2-user
          KEY: ${{ secrets.EC2_SSH_KEY }}