name: EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2-Deployment-Key }}

      - name: Deploy changes
        run: |
          ssh -o StrictHostKeyChecking=no user@<your-ec2-instance-ip> 'cd /path/to/your/project && git pull && pm2 restart server'
