name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Debug current directory
        run: |
          pwd
          ls -l

      - name: Print directory contents
        run: ls -l /home/ec2-user/Full-Stack-Project-Assessment-tree-main-server

      - name: Install dependencies and deploy to EC2
        working-directory: /home/ec2-user/Full-Stack-Project-Assessment-tree-main-server
        run: |
          npm install
          npm install -g pm2 
          git push origin main
          npm install
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2-Deployment-Key }} ec2-user@54.81.156.64 'cd /home/ec2-user/Full-Stack-Project-Assessment-tree-main-server && git pull && pm2 restart server'
